"""

Revision ID: 0e0b478b3406
Revises: 
Create Date: 2024-07-07 14:36:03.059321

"""

from typing import Sequence, Union

import sqlalchemy as sa
import sqlalchemy_utils
from alembic import op

from app.pg.models import ContractStatus

# revision identifiers, used by Alembic.
revision: str = '0e0b478b3406'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'contracts',
        sa.Column('contract_address', sa.String(), nullable=False),
        sa.Column('source_code', sa.String(), nullable=False),
        sa.Column('is_erc_20', sa.Boolean(), server_default='f', nullable=False),
        sa.Column('erc20_version', sa.String(), server_default='', nullable=False),
        sa.Column(
            'status',
            sqlalchemy_utils.types.choice.ChoiceType(ContractStatus),
            server_default='WAITS_PROCESSING',
            nullable=False,
        ),
        sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
        sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
        sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('contract_address'),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('contracts')
    # ### end Alembic commands ###
